# Generated by Django 3.0.2 on 2020-01-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('order', models.IntegerField()),
                ('day', models.IntegerField(db_index=True)),
                ('week', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True)),
                ('year', models.IntegerField(db_index=True)),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('subcategory', models.CharField(max_length=30)),
                ('ttype', models.CharField(db_index=True, max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'date', 'order'], name='financier_t_account_b07dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', 'subcategory'], name='financier_t_categor_2de750_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('account', 'date', 'order')},
        ),
    ]
