# Generated by Django 3.0.2 on 2020-01-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ttype',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
