# Generated by Django 3.0.2 on 2020-01-14 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0004_category_subcategory_titletosubcategorymap'),
    ]

    operations = [
        migrations.AddField(
            model_name='titletosubcategorymap',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='financier.SubCategory'),
            preserve_default=False,
        ),
    ]
