# Generated by Django 3.0.2 on 2020-01-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0005_titletosubcategorymap_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titletosubcategorymap',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
