# Generated by Django 3.0.2 on 2020-01-15 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0006_auto_20200115_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titletosubcategorymap',
            name='priority',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='titletosubcategorymap',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='financier.SubCategory'),
        ),
        migrations.AlterField(
            model_name='titletosubcategorymap',
            name='title_search_expression',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
