# Generated by Django 3.0.2 on 2020-01-15 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0007_auto_20200115_0803'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='financier_t_categor_2de750_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financier.SubCategory'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['subcategory'], name='financier_t_subcate_3ebdc7_idx'),
        ),
    ]
