# Generated by Django 3.0.2 on 2020-01-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0008_auto_20200115_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='title',
            field=models.CharField(max_length=245),
        ),
    ]
