# Generated by Django 3.0.4 on 2020-03-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0010_auto_20200312_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='filename',
            new_name='importfile',
        ),
    ]
