# Generated by Django 3.0.4 on 2020-03-12 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0011_auto_20200312_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='importfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financier.ImportSource'),
        ),
        migrations.DeleteModel(
            name='ImportFile',
        ),
    ]
