# Generated by Django 3.0.4 on 2020-03-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0012_auto_20200312_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='importfile',
            new_name='importsource',
        ),
    ]
