# Generated by Django 3.0.4 on 2020-03-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0013_auto_20200312_1630'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='financier_t_account_b07dd1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('account', 'date', 'title', 'ttype', 'value')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'date', 'title', 'ttype', 'value'], name='financier_t_account_264def_idx'),
        ),
    ]
