# Generated by Django 3.0.4 on 2020-03-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0014_auto_20200313_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('account', 'date', 'title', 'ttype', 'value', 'order')},
        ),
    ]
