# Generated by Django 3.0.4 on 2020-03-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0015_auto_20200316_2213'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='financier_t_account_264def_idx',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'date', 'title', 'ttype', 'value', 'count'], name='financier_t_account_fdf993_idx'),
        ),
    ]
