# Generated by Django 3.1.1 on 2021-01-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0017_auto_20200316_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('company_overview', models.JSONField(default="{'Name':'none', 'Symbol': 'none' }")),
            ],
        ),
        migrations.AddField(
            model_name='subcategory',
            name='include_in_budget',
            field=models.BooleanField(default=True),
        ),
    ]
