# Generated by Django 3.1.1 on 2021-04-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0018_auto_20210120_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='company_overview',
        ),
    ]
