###########
# BUILDER #
###########

# pull official base image
FROM python:3.8.0-alpine as builder

# set work directory
WORKDIR /usr/src/mysite

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

# lint
RUN pip install --upgrade pip
RUN pip install flake8
COPY . /usr/src/mysite/
RUN flake8 --ignore=E501,F401 .

# install dependencies
COPY ../requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/mysite/wheels -r requirements.txt


#########
# FINAL #
#########

# pull official base image
FROM python:3.8.0-alpine

# create directory for the app user
RUN mkdir -p /home/mysite

# create the app user
RUN addgroup -S mysite && adduser -S mysite -G mysite

# create the appropriate directories
ENV HOME=/home/mysite
ENV APP_HOME=/home/mysite/web
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles
WORKDIR $APP_HOME

# install dependencies
RUN apk update && apk add libpq
COPY --from=builder /usr/src/mysite/wheels /wheels
COPY --from=builder /usr/src/mysite/requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache /wheels/*

# copy entrypoint-prod.sh
COPY ./entrypoint.prod.sh $APP_HOME

# copy project
COPY . $APP_HOME

# chown all the files to the mysite user
RUN chown -R mysite:mysite $APP_HOME

# change to the app user
USER mysite

# run entrypoint.prod.sh
ENTRYPOINT ["/home/mysite/web/entrypoint.prod.sh"]
